### ISSUE TITLE
[suggetion] better way to use Drupal library files inside the component twig-files

### ISSUE THREAD

**Issue by LordRembo** [fourkitchens/emulsify#162]
So one issue I'm having, is I can't split the css-files per component without breaking PatternLab. The thing is, PatternLab loads all its css in 1 file and the same for the javascript. However, one strength of D8 is that you can attach libraries to any twig file, and thus to any component.
Sadly, 'attach_library' doesn't work in PatternLab, so I was a bit lost at how to achieve this.

My first attempt, was to have the PatternLab style.scss load everything, and only load some global styles in the site's style.scss. However, because of all the globbing and nesting of Sass-files, I quickly ran into Sass's limitations. It can't deal with imports of files that contain globbing.

My second idea, was to just hardcode a <link> tag in my components, in order to get my files into PatternLab and add some kind of if/else so it doesn't load it in Drupal. Right now I do a check for the htmlClass (which is 'pl' in PatternLab) but I'm sure there's other ways to do this.

I think the best solution would be for PatternLab to recognize 'attach_library' but I'm not sure how to approach this. In any case, the if/else check is not very efficient but it works for now.

`{% if htmlClass is defined and htmlClass == 'pl' %}`
 ` <link rel="stylesheet" href="../../../../dist/css/main-menu.css" type="text/css"/>`
`{% endif %}`

**Comment by evanmwillhite** [comment]
This is a great conversation to have! When it comes to JavaScript, we actually [do recommend](https://github.com/fourkitchens/emulsify/wiki/Drupal-Usage#javascript-in-drupal) the `attach_library` function on the Drupal side. That said, there has always been confusion around the global JS file and when to use that, so we're actually going to remove that [global file](https://github.com/fourkitchens/emulsify/blob/develop/components/_patterns/00-base/global/global.js)/[library](https://github.com/fourkitchens/emulsify/blob/develop/emulsify.libraries.yml#L5-L6) in [this babel/ES6](https://github.com/fourkitchens/emulsify-gulp/pull/64) PR. My initial thought with tht was it would make it easy to add JS to every page when you know you need it (e.g., the Typekit example), but we rarely use it and more often than not we see it misused for component-specific JS. On a side note, all JS currently gets put into a single JS file for Pattern Lab (separate gulp task handles that). I was thinking this would be fine initially because in some ways Pattern Lab is a single page app, but with the way it uses iframes for the components when drilling down, we could possibly refactor this at some point to use component-specific JS files. 

On the CSS side, we took the route of compiling to a single, minified CSS file served globally to both PL and Drupal. I have heard talk about component-izing the CSS as well and using `attach_library`, but I'd be interested to see performance statistics around this method vs. the single, minified file. I know the single, minified file will have a larger file size, but it seems to me the aggregation of multiple different CSS files would cause the user to grab a new resource fairly often which could negate (or even increase) the performance hit. If that is true, then this approach is more work and I personally would forego it. **BUT**, that said, I'm well aware this opinion is a personal preference and have no statistics of my own, so I was actually excited to see you start this conversation because I think the more voices it gets, the better. What do you think about this?

**Comment by LordRembo** [comment]
I'm inclined to take you position on the multiple stylesheets but it probably also depends on how many different pages a user visits in one go, how many components used, server response and lord know what else. That makes it difficult to test, I would imagine. However, with Drupal's per-page aggregation and caching, I don't think it'll make much difference either way.
The better way to beat performance, I think, is to add critical CSS & async your other CSS and fonts using javascript, which is completely out-of-scope for this and for which there are good write-ups elsewhere.
For me, it's mostly about having a better way to structure my files during development, so I thought I'd take the idea of components all the way and try splitting the assets a try as well. I'm not completely sold on the idea but it's worth testing it out.
I've got it working properly for the JS, using `attach_library` and removing the global file, as you mentioned.
I also think I get what you mean about misuse for component-specific JS. One think I'm seeing, is I have to be careful the JS doesn't load multiple times, for example. I still have to try out how that will work once I'm a bit further in development. One possibility, is to make good use of the `once()` functionality. Another thing I'm implementing, is using namespaces in the javascript files, so I can access helpers and such from a shared JS, more easily inside a component JS. But I'm not quite there yet.

**Comment by evanmwillhite** [comment]
It sounds like we're on the same page on a lot - I completely agree on the value of the critical CSS and async pieces in terms of performance. 

One thing I wanted to clarify though just to make sure I didn't mislead you is that we actually DO create separate SCSS and JS files inside our components. [Accordion](https://github.com/fourkitchens/emulsify/tree/develop/components/_patterns/02-molecules/accordion-item) is a good example of that. The idea is that you put all component-related files in one place. If you use BEM, you should be able to (in theory) completely remove a component at any time without impacting the rest of the system (obviously you would have to edit any files that include that component). Also, this means troubleshooting a component means going to one place. 

As for the misuse of global JS, I just meant we sometimes see people putting **all** the JS inside that global.js file instead of using component-specific JS files inside the component directory and `attach_library` to add them where needed on the Drupal side. I hope that helps clarify - sorry if I was too vague. Words are hard. :)

**Comment by LordRembo** [comment]
:D Not at all. I see what you mean with the Accordion. That is indeed a good example.
I'm going to see how well things work out when developing the way I've got it set up now. I'll revisit this if my setup proves to be worth the hassle. Thanks for taking the time explaining all this!
