### ISSUE TITLE
Rendering contextual links in blocks and nodes while keeping BEM classes

### ISSUE THREAD

**Issue by LordRembo** [fourkitchens/emulsify#178]
_One thing that threw me for a loop, is that the default components that used BEM classes sometimes didn't display any contextual links. And if they did, I wasn't sure how to add BEM classes to them.
Turns out I didn't really understand how contextual links worked and why attributes are important. So I hope this helps anyone else who got confused trying to get contextual links working with twig-components and BEM._

After some examining, I found that contextual links issues came from 1 or both of these things missing:
- {{attributes}} on the node or block itself, which renders data-attributes needed for the JS
- {{title suffix}}, which renders the actual links

In order to properly render these elements + keep using BEM classes, I just printed this on all wrappers for nodes, blocks and whatever component uses contextual menus:
`{% set extraClasses = attributes.class ? attributes.class|join(' ') %}`
`<div {{ bem(baseclass, modifiers, blockname, extraclasses) }} {{attributes|without('class')}}>`

So the extraClasses variable contains attributes.classes turned into a string and the rest of attributes are printed next to the BEM-generated classes.
I'd suggest adding something like this + a line of text to the default block and node twig-files as a helping hand.

**Comment by evanmwillhite** [comment]
I may be misunderstanding, but this shouldn't be necessary. Assuming you have the dependencies installed (see number 2 [here](https://github.com/fourkitchens/emulsify#in-a-composer-based-drupal-install-recommended)) - specifically the [Unified Twig Extensions](https://github.com/drupal-pattern-lab/unified-twig-extensions) module which enables Drupal to use any Twig extensions found in `/components/twig_components` that don't begin with 'pl_', the BEM Twig function _should_ add the classes to the Drupal Attributes object on any element it's placed on. That's one of the reasons we created it - simplifying the syntax around adding classes **both** to Pattern Lab and Drupal without affecting Drupal's existing classes. In the background, it basically takes any existing attributes and appends the classes added via the bem function and just returns all the attributes.

If this didn't occur in a certain situation or did something incorrect, post an issue in the [BEM Twig extension](https://github.com/drupal-pattern-lab/bem-twig-extension) repo. It's new since Emulsify 2.x, so it will likely need some refining over time.

Now with that said, you are definitely correct in that for contextual links to work, you still need the outer element in those template files with either the bem function or the attributes object printed (and `{{title suffix}}` where appropriate).

**Comment by LordRembo** [comment]
Aha, alright. I do have those dependencies installed but wasn't seeing this attributes/BEM output you describe. I'll do a bit of testing with the BEM function to see if I'm just missing something or the output is incomplete, and make a ticket in that other repo. Thanks for the clarification!
