### ISSUE TITLE
Drush 9 not supported with the "drush emulsify" command

### ISSUE THREAD

**Issue by SuperNami** [fourkitchens/emulsify#182]
Currently running `drush emulsify` in the emulsify folder (with emulsify.drush.inc inside it) doesn't work. I figured out that another command stopped working due to missing compatibility with Drush 9, which also seems to be the case for this project. Just thought I would document it for future improvements.

**Comment by thamas** [comment]
Just tried a Composer based Drupal 8.5 install with downgraded Drush (8.1.16) but it simply did not work. I think this issue should get a high(er) priority.

**Comment by ccjjmartin** [comment]
Just to throw it out there, the work around for this for now is to copy paste the whole Emulsify directory and customize it to fit your needs (delete components, change .info file to show your theme name, etc.).  The emulsify command just makes the process a bit easier.  I looked into this and the drush command will need to be completely rebuilt from the ground up because Drush changed the way they reference files (drush.inc to drush.services.yml).

We should likely update the readme for now to show a manual setup process.

**Comment by thamas** [comment]
Yes, I know it is mostly about copying. The tricky part is the renaming: what and where should be renamed. That is why I miss the drush command.

**Comment by ccjjmartin** [comment]
Grumbling about Drush 9 ...  If we want to get this working we will have to setup a sister "module" for Emulsify just for the drush command because services aren't supported in themes, only in modules.  We had originally considered using Drupal console for similar functionality to set this up but same issue (modules only).  I am now leaning towards a node / gulp command because it doesn't really care about Drupal at all will just copy / edit the files which is all we want it to do.

**Comment by thamas** [comment]
Thanks for the info @ccjjmartin!

**Comment by ccjjmartin** [comment]
@thamas I went for a plain PHP script for the rebuild.  Feel free to test it out: https://github.com/fourkitchens/emulsify/pull/218

**Comment by ccjjmartin** [comment]
Example useage:
`php emulsify.php test2 --slim --machine-name awesome3 --path contrib --description "My really awesome description"`

**Comment by ccjjmartin** [comment]
Just in case anyone is interested this seems to be what is required for Drush 9 support:
http://gbyte.co/blog/creating-drush-9-commands-and-porting-legacy-commands

Seems like it would require every project to edit composer.json ...

**Comment by igorlakic** [comment]
@thamas Do you get this warning message #209? If you're using PHP 7.2 it will definitely not work. With 7.1 and drush 8.1.16 it works as expected.

**Comment by thamas** [comment]
@igorlakic No. It was a different one. PHP 7.1.12. New, Composer based Drupal 8.5 install (includes Drush 9.2.x). Downgraded to Drush 8.1.16 with Composer.

**Comment by thamas** [comment]
@igorlakic It was: 
> PHP Fatal error: Class 'Drush\Commands\DrushCommands' not found in … 

(can't remember the "in" part).   

Similar to this: https://www.drupal.org/project/migrate_run/issues/2917702

**Comment by igorlakic** [comment]
Hmm, that's weird... I got a similar error message before the downgrade to Drush 8.1.16 but after that, `drush emulsify` worked. It seems that Drush 9 brought pile of issues unfortunately 🤔

**Comment by evanmwillhite** [comment]
This should have been fixed since moving to the php script. Feel free to reopen if the original issue exists. If you find specific bugs with the new script, let's open new issues. Thanks!
