### ISSUE TITLE
SCSS in two different places is confusing, has a lot of duplication

### ISSUE THREAD

**Issue by froboy** [fourkitchens/emulsify#191]
The project is using two different ways of including SCSS:
- in the pattern directories
- in the `css/scss/*` directories. 

(this is a decision that Pattern Lab also leaves as an exercise for the implementer) It seems like it'd help projects get started (and also make for less code) to make a decision about one or the other. Personally, I'm a fan of keeping styles with their components. It seems like if a few basic sheets (`_mixins.scss`, `_variables.scss`, maybe a new `_global.scss`) moved to `_patterns/00-base/global/` then we could get rid of the `css` directory altogether? 

I'm interested to hear thoughts or how other folks have dealt with this.

**Comment by froboy** [comment]
Sorry, just missed that `_patterns/00-base/_01-variables.scss`, `_breakpoints.scss`, and `_mixins.scss` already exist... so there's really no reason to have the entire duplicate set of things.

**Comment by evanmwillhite** [comment]
The `css/` directory is for Pattern Lab itself (not your components), but I think the scss files here could actually be removed. Unless someone wanted to tweak the look/feel of Pattern Lab itself using those scss files (which 1. would need a separate scss task because Emulsify is currently not interested in compiling those and 2. could be done by just editing the .css files themselves), and I'm thinking this might be an edge-case, so we could probably get rid of them. 

Also, it might help to document that the styes in the `css/` dir are for Pattern Lab itself in a readme file inside that directory to steer people away from using it. 

What do you think? Thanks for bringing attention to this!

**Comment by froboy** [comment]
@evanmwillhite thanks for the quick feedback. See the PR ⬆️ .
