### ISSUE TITLE
Data Inheritance

### ISSUE THREAD

**Issue by froboy** [fourkitchens/emulsify#200]
One of the pieces that I've seen in some other projects but seems to be missing in Emulsify is data inheritance. ([Many words here.](http://www.aleksip.net/data-inheritance-in-pattern-lab)) Is that something that's been discussed in the context of the project before? Any reasoning behind whether or not to include it?

I _think_ (unless I'm missing something) that there's a lot of duplication of content here, for example, the `info_box_grid` content exists as [yml in the root pattern](https://github.com/fourkitchens/emulsify/blob/develop/components/_patterns/03-organisms/info-box-grid/info-box-grid.yml) but also as [json in the template](https://github.com/fourkitchens/emulsify/blob/develop/components/_patterns/04-templates/example/example.twig#L9).

Thanks!

**Comment by amazingrando** [comment]
@froboy This is on our minds as well. This project grew organically out of a need that we had, so there is some legacy stuff we're working to streamline.

**Comment by froboy** [comment]
@amazingrando sweet. Any thoughts on which direction you might be thinking? I've got a project we're using this on and I'll prob do some work on one path or another (Data Inheritance or Data Transform) in the very near future and I'd be happy to contribute it back if it fits in with your vision.

**Comment by amazingrando** [comment]
@froboy No idea at the moment.

**Comment by evanmwillhite** [comment]
We have discussed this a bit internally and weren't certain we wanted to add this overhead, because sometimes you want data to inherit (or be shared between components) and sometimes you don't want it to. Instead of adding another dependency to automatically handle this which may or may not conflict with situations below, we just decided to stick with the following approaches which don't require another library:

Situation 1: **Inherit or share** - If data inheritance or shared data is needed, use global files in the [`_data` directory ](https://github.com/fourkitchens/emulsify/tree/develop/components/_data) or of course you can just put data directly into Twig files.
Situation 2:  **Do not inherit or share** - keep data in YAML files

I'm going to close this issue, but please don't see that as ending the conversation. If you find a situation that falls outside of these above or have an argument against this approach, please feel free to reopen!
