### ISSUE TITLE
Can't use "Crimson Text" Google font CSS due to gulp-clean-css bug

### ISSUE THREAD

**Issue by nsciacca** [fourkitchens/emulsify#201]
I'm trying to use Google's font "Crimson Text", however the compiled CSS is replacing "Crimson" with the hexcode "#dc143c". I started poking around the gulp-css.js file and found if I removed the call to "cleanCSS" (gulp-clean-css) then it works fine. 

I tried setting up a simple node project with gulp-clean-css and replicated the error, apparently in the default optimization (level 1) there's a shorten-hex.js file that maps these color keywords to their hex values. 

I've logged [a new issue on that page](https://github.com/scniro/gulp-clean-css/issues/54). Hopefully they'll fix it on their end but for the moment I'm leaving the cleanCSS commented out. Maybe the config for emulsify should be updated to allow passing options to cleanCSS, in which we could specify the level of optimization.

**Comment by amazingrando** [comment]
@nsciacca That's a bummer. Thanks for bringing this to our attention. 

I'll create an issue for passing options to cleanCSS and add it to the queue. If you fix it before us, submit a pull request and I'll review that quickly.

**Comment by evanmwillhite** [comment]
I echo @amazingrando's sentiments - sorry about this weird, annoying bug. I did just notice that if you want to update to using the master version of Clean CSS, there is [this addition](https://github.com/jakubpawlowicz/clean-css#how-to-keep-a-css-fragment-intact) that allows you to comment out CSS code that you want clean css to ignore.

I moved this over to [Emulsify Gulp's queue](https://github.com/fourkitchens/emulsify/issues/201) just to keep the history but lowered priority since it appears there is a workaround.
