### ISSUE TITLE
JS error in PL style-guide

### ISSUE THREAD

**Issue by shaal** [fourkitchens/emulsify#258]
In the public styleguide of emulsify -
Atoms -> Images -> Icons
https://fourkitchens.github.io/emulsify/pattern-lab/public/?p=atoms-icons

The page loads with some errors -
```
    at main-menu.js:25
    at main-menu.js:18
(anonymous) @ main-menu.js:25
(anonymous) @ main-menu.js:18
```

**Comment by ModulesUnraveled** [comment]
I think this is because Pattern Lab is loading all JS even when it's not needed. So on the "Images" page, the main-menu.js file is loaded, but it can't find the menu elements so it's reporting an error. This should be addressed by https://github.com/fourkitchens/emulsify/pull/245. So, let's see if we can move that forward!

**Comment by evanmwillhite** [comment]
That is correct - those errors are removed in that instance.
