### ISSUE TITLE
SVG icons ignoring the directory structure of the theme

### ISSUE THREAD

**Issue by shaal** [fourkitchens/emulsify#266]
While running `gulp compile && gulp build` locally works just fine,
(sprite is generated and icons can be seen in the styleguide)

When trying to view the public styleguide, icons are not showing up.
https://fourkitchens.github.io/emulsify/pattern-lab/public/?p=atoms-icons

It tries loading the sprite file from (404)
`https://fourkitchens.github.io/dist/img/sprite/sprite.svg#bars`

but the actual location of the sprite file is -
`https://fourkitchens.github.io/emulsify/dist/img/sprite/sprite.svg#bars`

**Comment by ModulesUnraveled** [comment]
We're actually aware of this one. Icons work in Pattern Lab, and In Drupal, but not in github pages.

Line 13 here defines the path for Drupal: https://github.com/fourkitchens/emulsify/blob/develop/components/_patterns/01-atoms/04-images/icons/_icon.twig#L13
`{% set icon_url = icon_url|default('/themes/custom/YOURTHEME/dist/img/sprite/') %}`

Line 2 here overrides it for Pattern Lab: https://github.com/fourkitchens/emulsify/blob/develop/components/_data/paths.json#L2
`"icon_url": "/dist/img/sprite/"`

But because the github pages deployment adds the repo name (or something), in this case `/emulsify` to the beginning of the directory structure, it doesn't match either of those two paths.

We decided to table this, since it works in every PL instance _except_ github pages, and will also work in Drupal. We don't use the github pages instance for anything, it's really just icing on the cake for us, so it was a low priority.

Now that you know where the paths are defined, and what's causing the issue, if you can think of a way to make it work, I'm all ears!

**Comment by shaal** [comment]
Thank you.
In our case, it affects the public PL styleguide we want to have on the website

**Comment by evanmwillhite** [comment]
@shaal if it helps, I think if you use a custom domain for your github pages repo everything will work OK. I do want to fix this though.
