### ISSUE TITLE
Error during scripts-styelguide.js  concatenation

### ISSUE THREAD

**Issue by obriat** [fourkitchens/emulsify#296]
I try to include the [choices.js lib](https://github.com/jshjohnson/Choices) into a template. I simply added the [choices.min.js] (https://github.com/jshjohnson/Choices/blob/master/assets/scripts/dist/choices.min.js) into my template dir.

After the gulp task processing, the  lib was well included into scripts-styleguide.js but some variables were changed to undefined triggering errors, e.g:
The wrapping function `! function(e, t) {...}(this, function(){...});` was converted to `! function(e, t) {...}(undefined, function(){...}); `.

It seems linked to the babel transtyping, there's maybe another way to include these kind of lib (which is already babelize/webpacked) but my javascript is a bit rusty, so could someone give me a workaround ?

If it's a common case maybe the doc should be updated ?

**Comment by obriat** [comment]
The Drupal part is working fine, but I want the lib to be also loaded into the styleguide, so I can  visualized the new css styles added by the lib and test the js behaviours. 

I follow  the [doc ](https://github.com/fourkitchens/emulsify/wiki/Orientation#js)and respect the  accordion component code (just put my lib into the pattern dir), but the concatenation to [scripts-styelguide.js](https://github.com/fourkitchens/emulsify/wiki/Orientation#js) broke the lib code.

If you want to reproduce the problem, just add this file https://github.com/jshjohnson/Choices/blob/master/assets/scripts/dist/choices.min.js in to one of your component dir and add theses line into the according twig.
```
<select class="js-choice">
  <option value="1">one</option>
</select>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const choices = new Choices('.js-choice');
  });
</script>

```

You should notice errors in the js console

**Comment by evanmwillhite** [comment]
@obriat we've updated our asset handling quite a bit in more recent versions to use this [`attach_library`](https://github.com/drupal-pattern-lab/attach-library-twig-extension) function. Not sure if that will solve your issue (haven't run into this one myself yet), but if it doesn't, you can also move library references to a separate script tag in the [head/foot](https://github.com/fourkitchens/emulsify/tree/develop/components/_meta) of Pattern Lab so that they fall outside Emulsify's build process.

I love the idea of putting your library alongside your component, but expecting a compiled/minified file to be transpiled/re-minified correctly might be a stretch, so I'd probably separate that out to the head/foot if it caused me issues.
