### ISSUE TITLE
Keep Node and PHP separate

### ISSUE THREAD

**Issue by dalin-** [fourkitchens/emulsify#345]
Typical local development these days involves Docker with separate containers for PHP and Node.  Emulsify seems to be currently incompatible with this because `npm install` (which would be run in a node-only container) will run `pattern_lab.sh` which in turn calls `composer create-project` (but there's no PHP in the node container, let alone Composer).  

Is there a way to separate these two?

**Comment by ludal74** [comment]
Unfortunatly, the problem is also on the pattern lab side, which mix node and PHP functionalities in the npm start method.

The only way to make it work is to build a container embedding PHP, composer and Node as explained here : 

https://savaslabs.com/2017/02/20/drupal-docker-pattern-lab.html

But I’m agree with you, this architecture is not designed for dockerized applications

**Comment by evanmwillhite** [comment]
I have always mourned the mixture of languages in the installation process, and while we won't put work towards this on the current version of Emulsify, the next version will be a Node-based installation.
