### ISSUE TITLE
Need to refactor all default components

### ISSUE THREAD

**Issue by ModulesUnraveled** [fourkitchens/emulsify#48]
Updating all default components based on latest best practices.

## Todo
- Atoms:
  - forms (Evan)
  - tables (Evan)
  - menu (Brian)
  - _field-wysiwyg.twig
  - _field.twig
  - _table.twig
- Molecules
  - accordion-item (Evan)
  - info-box (Brian)
  - menus (Brian)
    - breadcrumbs
    - inline-menu
    - tabs
  - pager (Chris)
  - status (Brian)
  - _block.twig
  - _search-result.twig
- Organisms
  - Accordion (Evan)
  - Card Grid (Brian)
  - Info Box Grid (Brian)
  - Site (Evan)

## Done
- Atoms:
  - ~links~
  - ~text~
  - lists
    - Need to finalize lists (how to use items)
  - ~images~
  - ~buttons~
  - ~video~
- Molecules:
  - ~card~
- Templates (all) - We don't have any.
- Pages (all) - We don't have any.

**Comment by rupl** [comment]
I could take a stab at this. There are a lot of gotchas that frustrated me during my first implementation. A quick example using a heading (they're all copy-pasted so they all exhibit these inconsistencies)

```twig
{#
/**
 * Available variables:
 * - h2_base_class - base class name
 * - heading_2_modifiers - array of modifiers to add to the base classname
 * - heading_2_blockname - blockname prepended to the base classname
 * - heading_2_url - (optional) the url the heading should poing to
 * - heading_2 - the content of the heading (typically text)
 */
#}
```

I feel like it should be more like this:

```twig
{#
/**
 * Available variables:
 * - h2_baseclass - base class name
 * - h2_modifiers - ARRAY of modifiers to add to the base classname
 * - h2_blockname - blockname prepended to the base classname
 * - h2_content - the content of the heading
 *
 * - h2_url - (optional) the url the heading should point to
 * - h2_id - (optional) an HTML ID for the heading
 */
#}
```

- Prefix with the tag name when it's an HTML tag. Less typing and faster perusing. 
- Group optional stuff below and prefix description with `(optional)`
- Capitalize when data type is not a string, e.g. `ARRAY` in my comment block above.
- Stick with `TAG_content` for innerHTML variable. Many higher-level components do it but lots of atoms do not. Made me absolutely nutty my first week using Emulsify. A newbie doesn't know whether it's their fault or not, and it's definitely the lib in this case.
- Some might consider this minor, but I find it highly convenient when a template has variables with equal numbers of word boundries. In the age of multi-cursor editors we expect stuff to be convenient when editing groups of similar variables, but `TAG_base_class` is an outlier. Now, the caveat is that I have underscore added to my word boundry character list (it's not by default in OSX) but I'd also say that's a lifehack every dev needs ;)

**Comment by rupl** [comment]
Another thing to do is to get rid of all that boilerplace with the base_class_var and modifiers and so forth. That needs to be held in some kind of function (I don't know the twig word) so you just pass it into a standardized processor which accepts the three BEM variables (`baseclass`, `modifiers`, `blockname`)

In order to follow conventions on my project, I'm very frequently having to manually paste in this mess:

```twig
{% set heading_2_base_class_var = heading_2_base_class|default('heading-2') %}
{% set heading_2_blockname_var = heading_2_blockname|default('heading-2') %}
<h2 class="{{ heading_2_base_class_var }}{% for modifier in heading_2_modifiers %} {{ heading_2_base_class_var }}--{{ modifier }}{% endfor %}{% if heading_2_blockname_var %} {{ heading_2_blockname_var }}__{{ heading_2_base_class_var }}{% endif %}">
...
</h2>
```

I used the short version, as opposed to the "Full BEM" logic which combines all three to get classes like `blockname__baseclass--modifier` (or what if you want `blockname--modifier__baseclass`). Either one is pretty gross and is _almost demanding_ that a human make a typo. This should be condensed to the following:

```twig
<h2 {{ BEMify('heading_2') }}>
...
</h2>
```

The argument can be the prefix which namespaces these variables, so in a perfect world you don't even have to supply them, the scope of the twig file would be enough.

**Comment by evanmwillhite** [comment]
@rupl I love these suggestions. There's actually an [approved PR](https://github.com/fourkitchens/emulsify/pull/78) up for this last one, but I haven't merged b/c we need a solution for the Drupal side (a module that adds this Twig function to Drupal as well and documentation to suit). There's actually a project up in a PR for a module that does this automatically for _all_ functions (and filters, tags) in the Pattern Lab `twig_components` dir that I just haven't had time to test. We would need to customize for our purposes because we use `components` instead of `source` for the PL directory name but that shouldn't be hard.

But yea, this would greatly simplify that syntax and get rid of much of the copy/paste refactor work.

**Comment by rupl** [comment]
nice, yeah I have to say this really slowed me down at first so it's good to solve it. Particularly since the recommended usage of Emulsify is to clone and commit, with no possibility of receiving upgrades. I'll add some feedback over there.

**Comment by evanmwillhite** [comment]
We've done a lot of these and we agreed to break the rest out into smaller issues soon.
