### ISSUE TITLE
Remove/Update/Enforce Sassdoc

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify#51]

**Comment by ModulesUnraveled** [comment]
We originally talked about removing Sassdoc, but there's been some discussion lately of utilizing it as it's designed. So, we need to revisit this discussion and decide one way or another.

**Comment by evanmwillhite** [comment]
I'd rather see us use a linting tool than a sass documentation tool. Not to mentioned we're discussing moving away from sass to just postcss plugins as a base anyway, so I say we remove it.

**Comment by amazingrando** [comment]
Remove sassdoc. I strongly recommend [stylelint](https://github.com/stylelint/stylelint) for linting.

**Comment by EvanLovely** [comment]
Stylelint's worked well for us. I'd suggest putting in instructions in the readme on how to disable just a few lines via comments so when people hit that rule that they are triggering but they can't refactor, they use those instead of turning it off for the whole project.

https://github.com/phase2/pattern-lab-starter#disabling-stylelint-rules-for-a-certain-section

Another trick to get right is having it fail (exit non-zero) when ran by itself and an error is found so that CI systems report correctly and having it so when it's triggered via watches to not have it exit non-zero cause it sucks to have restart gulp after a stylelint warning. Hit me up if you want some pointers on getting this part right.

**Comment by amazingrando** [comment]
@EvanLovely I like the idea of having it exit non-zero for watches. Do you have a public code sample  that you can point me to?

**Comment by EvanLovely** [comment]
You definitely want it to report an error in the Terminal, but you want to avoid someone hitting save after typing an error, then seeing it immediately, correcting it and then hitting save again but by then Gulp has thrown an error and isn't running anymore.

Here's how I've implemented it: I've made a main function that you can call with true or false on where it will exit on error. The watch one triggers it with false and the regular one called with `gulp validate:css` triggers it with true: https://github.com/phase2/p2-theme-core/blob/master/lib/css.js#L67-L84

**Comment by evanmwillhite** [comment]
Ok, will remove following https://github.com/fourkitchens/emulsify/pull/79 getting merged
