### ISSUE TITLE
Publish on packagist.org

### ISSUE THREAD

**Issue by zaporylie** [fourkitchens/emulsify#81]
Repository already contains package definition in composer.json file. Natural next step would be to publish it on packagist.org OR change vendor name to `drupal` and publish on drupal.org.

**Comment by C13L0** [comment]
@ModulesUnraveled 
I really love the idea of stripping out the example components and placing them in an Example directory. The reason is because...I DO want all of the updates =)

If you were able to separate the example components and place it on drupal.org, there is no doubt it would become the defacto starterkit much as Omega 4, Bootstrap, and Zen were for D7.

**Comment by ModulesUnraveled** [comment]
@C13L0 Thanks for your input! That's definitely the direction I'm leaning personally. But this isn't _my_ project. :) So we need to get feedback from everyone involved. It would definitely fit the "Install everything with Composer" pattern that D8 is tending toward (and that I'm in favor of.)

**Comment by ModulesUnraveled** [comment]
One thing I just remembered though (and why we haven't just pulled the trigger) is that the `components`, or at least the `_patterns` directory **should** be in your Git repo so that you can share your custom components with other developers on your team. And if we're installing Emulsify with Composer, that directory would get overwritten each time.

One suggestion to approach that has been to install Emulsify in the `/themes/contrib` directory (as expected) but have it point to a `/themes/custom/components` directory where your custom implementation of components lives.

Seems a little messy though, and I don't know the _right_ answer at this time.

**Comment by amazingrando** [comment]
Work continues to resolve this issue but we aren't there yet. Just an FYI.

**Comment by evanmwillhite** [comment]
This has been done now and [recommended usage in readme](https://github.com/fourkitchens/emulsify#drupal-specific-installation) has been updated accordingly.
