### ISSUE TITLE
Documentation on how to add new component to _patterns/00-base/global

### ISSUE THREAD

**Issue by C13L0** [fourkitchens/emulsify#83]
I would like to separate out global colors instead of having them all grouped into one (01-colors). Such as:

```
_patterns/
--00-base/global/
----01-colors-brand/
----02-colors-neutral/
----03-colors-utility/
----04-animations/
```

The new color components are ignored and the json file is not generated. I'm not having any issues creating new components in Molecules. What am I missing?

Thanks!
Cielo

**Comment by evanmwillhite** [comment]
Good question, and I like how you are separating out your colors/animations. You can actually add new components anywhere, but colors have a bit more magic going on. You'll notice in [this file in emulsify-gulp](https://github.com/fourkitchens/emulsify-gulp/blob/develop/gulp-config.js#L87-L92) that it references a specific file to parse the SCSS to turn it into JSON automatically so that the colors will just automatically appear in PL.

This file is meant to be used either globally from within emulsify gulp (default) or locally to tweak it to your needs. I would recommend that route for you, and [here are some instructions](https://github.com/fourkitchens/emulsify/wiki/Gulp-Config#local-configuration) for copying it down into the root of your directory and tweaking it. The instructions are for a different example, but you will want to do step 1 pretty much the same (copy the file down to the root of your Emulsify installation and grab the contents from the original). 

Also, if it helps for debugging purposes, [here is the section of the gulp tasks](https://github.com/fourkitchens/emulsify-gulp/blob/develop/gulp-tasks/gulp-pattern-lab.js#L54-L86) that handles that SCSS to JSON process.

**Comment by C13L0** [comment]
Thank you so much for the very detailed reply. This is was exactly what I was looking for :D
